PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX reason: <http://data.lblod.info/reason#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?s ?p ?o WHERE
{
    {
         SELECT  DISTINCT  ?s
                           ?p
                           ?o
          WHERE
             {
                GRAPH <${graphReason}>
                 {
                   ?s a reason:Reason.
                   ?s ?p ?o.
                 }
             }
       ORDER BY ?s ?p ?o
     }

}  limit ${limitSize?string.computer} offset ${offsetNumber?string.computer  }
