<#assign data = dataJson?eval_json>
<#assign id = _uuid()>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX reason: <http://data.lblod.info/reason#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
        GRAPH <${graphReason}> {
          <http://whatever.com/reasons/${id}> a  reason:Reason;
                                       mu:uuid "${id}";
                                        reason:requester  "${data.requester}";
                                        reason:property  "${property}";
                                        reason:operation  "${operation}";
                                        reason:nsType "${nsType}";
                                        reason:date "${time}"^^xsd:dateTime;
                                        reason:reasonPhrase  "${data.reason}".
        }
      }
